apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb-data   #hostpath means: on the node where the pod is running,#
                              #a folder from that node's own filesystem is mounted into the pod


