apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dashoboard-demo
type: Opaque
data:                        #MagoDB username ans password base64 encoded
  username: YWRtaW4=
  password: cGFzc3dvcmQxMjM=
 